### ISSUE TITLE
Mac failure to launch, likely cause = newer 64-bit SWT

### ISSUE THREAD

**Issue by justingeeslin** [cogtool/cogtool#10]
Running cogTool on a modern mac produces the following error. Maybe an updated API for handing application menus?

```
Catching error...
java.lang.NoSuchMethodError: commandProc
	at org.eclipse.swt.internal.Callback.bind(Native Method)
	at org.eclipse.swt.internal.Callback.<init>(Callback.java:137)
	at org.eclipse.swt.internal.Callback.<init>(Callback.java:88)
	at org.eclipse.swt.internal.Callback.<init>(Callback.java:66)
	at edu.cmu.cs.hcii.cogtool.util.MacOSXPlatform.initPlatformMenu(MacOSXPlatform.java:149)
	at edu.cmu.cs.hcii.cogtool.ui.RootUI.<init>(RootUI.java:202)
	at edu.cmu.cs.hcii.cogtool.controller.RootController.<init>(RootController.java:119)
	at edu.cmu.cs.hcii.cogtool.CogTool.main(CogTool.java:260)
Version: [none specified]
Mac OS X, version 10.15.4, JVM 1.8.0_201 (Oracle Corporation)
```

A little more debugging reveals:
```
Unresolved compilation problems: 
	OS cannot be resolved
	OS cannot be resolved to a variable
	HICommand cannot be resolved to a type
	HICommand cannot be resolved to a type
```

The imports in the class reveal a reliance on carbon instead of the more modern cocoa. Does not seem to be available on a modern mac.
```java
import org.eclipse.swt.internal.carbon.HICommand;
import org.eclipse.swt.internal.carbon.OS;
```

**Comment by justingeeslin** [comment]
This code that relies on carbon seems to be only drawing the Mac app menus. I have a working version in [my fork's feature branch ](https://github.com/justingeeslin/cogtool/tree/feature/modernizing-macos-app-menus). But I think there is still something strange going on (like the menus aren't openable without blurring and refocusing the app). But I've fixed the crash, and created a version of working About and Preferences menus in Cocoa. PR coming soon.
