### ISSUE TITLE
Building CogTool on Mac - problem and hacky solution

### ISSUE THREAD

**Issue by azmr** [cogtool/cogtool#4]
Problem
---------
- Similar to #3, JRE/JDK 1.5/1.6/...? is needed to build with `javac`.
- Eclipse Indigo is difficult to install (I found the following solution before succeeding to do so).
- The latest Eclipse doesn't seem to have the same layout as described in [`cogtool/documentation/Processes/configuring-development-machines.txt`](https://github.com/cogtool/documentation/blob/master/Processes/configuring-development-machines.txt).
- The same documentation suggests building with Eclipse on Mac, but `ant` works just as well (and I personally found it much easier to set up - `brew install ant`)
- The build seems to assume you are using SVN, presumably a remnant from before it was on git?

Solution
--------
- Download and install [Java 1.6](https://support.apple.com/kb/DL1572).
- Edit `build.xml`:
    - Add `<property name="compiler" value="/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/bin/javac" />` (or wherever your `javac` is kept). I did this on the line before `<property name="jlevel"...`.
    - Edit `<property name="jlevel" value="1.5" />` and change the value as appropriate (i.e. `<property name="jlevel" value="1.6" />`). This didn't seem to be 100% necessary to build the file, but it might affect something.
    - There are 2 lines with `srcdir="${srcroot}"` and `srcdir="${macsrcroot}"`. Add these 2 parameters to both of them: `executable="${compiler}" compiler="modern"`. i.e.
```
<target name="compile" description="Compiles java source with javac.">
    <javac srcdir="${srcroot}" destdir="${builddir}" debug="on" fork="true" executable="${compiler}" compiler="modern" source="${jlevel}" target="${jlevel}">
...
    </javac>

    <javac srcdir="${macsrcroot}" destdir="${builddir}" debug="on" fork="true" executable="${compiler}" compiler="modern" source="${jlevel}" target="${jlevel}">
...
```
- 
   - Delete or comment out the following lines:

```
<condition property="svnversion" value="/usr/local/bin/svnversion" else="svnversion">
    <and>
        <os family="mac" />
        <os family="unix" />
    </and>
</condition>

<exec executable="${svnversion}" vmlauncher="true" resolveexecutable="true" outputproperty="revision">
    <arg file="${basedir}" />
</exec>
```
- You can then run `ant` from the command line in the base directory of the repository, and it should build successfully.

**Comment by justingeeslin** [comment]
Can reproduce. 

I am not a svn user and the build process seems to fail on the svn step.

Running `ant` generates the following: 

```
Buildfile: /Users/Skyward/cogtool/build.xml
[defaultexcludes] Current Default Excludes:
[defaultexcludes]   **/%*%
[defaultexcludes]   **/.git/**
[defaultexcludes]   **/SCCS
[defaultexcludes]   **/.bzr
[defaultexcludes]   **/.hg/**
[defaultexcludes]   **/.bzrignore
[defaultexcludes]   **/.git
[defaultexcludes]   **/SCCS/**
[defaultexcludes]   **/.hg
[defaultexcludes]   **/.#*
[defaultexcludes]   **/vssver.scc
[defaultexcludes]   **/.bzr/**
[defaultexcludes]   **/._*
[defaultexcludes]   **/#*#
[defaultexcludes]   **/*~
[defaultexcludes]   **/CVS
[defaultexcludes]   **/.hgtags
[defaultexcludes]   **/.svn/**
[defaultexcludes]   **/.hgignore
[defaultexcludes]   **/.svn
[defaultexcludes]   **/.gitignore
[defaultexcludes]   **/.gitmodules
[defaultexcludes]   **/.hgsubstate
[defaultexcludes]   **/.gitattributes
[defaultexcludes]   **/CVS/**
[defaultexcludes]   **/.hgsub
[defaultexcludes]   **/.DS_Store
[defaultexcludes]   **/.cvsignore

clean:

compile:
    [javac] /Users/Skyward/cogtool/build.xml:67: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 461 source files to /Users/Skyward/cogtool/build
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.5
    [javac] warning: [options] source value 1.5 is obsolete and will be removed in a future release
    [javac] warning: [options] target value 1.5 is obsolete and will be removed in a future release
    [javac] warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 4 warnings
    [javac] /Users/Skyward/cogtool/build.xml:72: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 1 source file to /Users/Skyward/cogtool/build
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.5
    [javac] warning: [options] source value 1.5 is obsolete and will be removed in a future release
    [javac] warning: [options] target value 1.5 is obsolete and will be removed in a future release
    [javac] warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
    [javac] 4 warnings
     [copy] Copying 406 files to /Users/Skyward/cogtool/build/edu/cmu/cs/hcii/cogtool/resources

package:
      [jar] Building jar: /Users/Skyward/cogtool/dist/CogTool.jar
     [copy] Copying 3 files to /Users/Skyward/cogtool/dist/CogTool.app
     [copy] Copying 1 file to /Users/Skyward/cogtool/dist/CogTool.app/Contents/MacOS
     [copy] Copying 1 file to /Users/Skyward/cogtool/dist/CogTool.app/Contents/MacOS
     [copy] Copying 1 file to /Users/Skyward/cogtool/dist/CogTool.app/Contents/Resources/Java
     [copy] Copying 8 files to /Users/Skyward/cogtool/dist/CogTool.app/Contents/Resources/Java

BUILD FAILED
/Users/Skyward/cogtool/build.xml:160: Execute failed: java.io.IOException: Cannot run program "/usr/local/bin/svnversion": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.apache.tools.ant.taskdefs.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:58)
	at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:428)
	at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:442)
	at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:628)
	at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:669)
	at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:495)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	at org.apache.tools.ant.Main.runBuild(Main.java:851)
	at org.apache.tools.ant.Main.startAnt(Main.java:235)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 23 more

Total time: 13 seconds

```

**Comment by justingeeslin** [comment]
Removed the lines suggested above in PR #14 . This should close this issue. I did not reproduce the other aspects concerning `javac`. 

```xml
<condition property="svnversion" value="/usr/local/bin/svnversion" else="svnversion">
    <and>
        <os family="mac" />
        <os family="unix" />
    </and>
</condition>

<exec executable="${svnversion}" vmlauncher="true" resolveexecutable="true" outputproperty="revision">
    <arg file="${basedir}" />
</exec>
```
