### ISSUE TITLE
CogTool failure to launch,  Cannot run Java in 32 bit mode, macOS Catalina

### ISSUE THREAD

**Issue by justingeeslin** [cogtool/cogtool#6]
Opening CogTool on a modern mac crashes after a few seconds, appearing in the dock and then disappearing. 

Under the hood, running `cogtoolstart` from the command line reveals that "Cannot run Java in 32 bit mode. Continuing in 64 bit mode." This inability to run Java in 32 bit mode is recent, new in macOS Catalina per [Apple's announcement here](https://support.apple.com/en-us/HT208436).

```
macos@macos-10 MacOS % ./cogtoolstart         
Cannot run Java in 32 bit mode. Continuing in 64 bit mode.
Catching error...
java.lang.UnsatisfiedLinkError: Cannot load 32-bit SWT libraries on 64-bit JVM
	at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
	at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
	at org.eclipse.swt.internal.C.<clinit>(Unknown Source)
	at org.eclipse.swt.widgets.Display.createDisplay(Unknown Source)
	at org.eclipse.swt.widgets.Display.create(Unknown Source)
	at org.eclipse.swt.graphics.Device.<init>(Unknown Source)
	at org.eclipse.swt.widgets.Display.<init>(Unknown Source)
	at org.eclipse.swt.widgets.Display.<init>(Unknown Source)
	at org.eclipse.swt.widgets.Display.getDefault(Unknown Source)
	at edu.cmu.cs.hcii.cogtool.util.WindowUtil.<clinit>(WindowUtil.java:208)
	at edu.cmu.cs.hcii.cogtool.view.RootView.<init>(RootView.java:84)
	at edu.cmu.cs.hcii.cogtool.ui.RootUI.<init>(RootUI.java:161)
	at edu.cmu.cs.hcii.cogtool.controller.RootController.<init>(RootController.java:96)
	at edu.cmu.cs.hcii.cogtool.CogTool.main(CogTool.java:287)
```

**Comment by justingeeslin** [comment]
The crash is caused by an older version of SWT which is 32-bit only. #11 updates the SWT included with CogTool with a 64-bit compatible version. Once #11 lands in master (with all the other kinks worked out #10) then this will be resolved.
